# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

set -o vi

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

# Telcobase env
export TELCOBASE_CONF=~/mmdb/INI/telcobase.conf
#export TELCOBASE_DIR=~/workspace/telcoware/telcobase3
#export TELCOBASE_DIR=~/workspace/clion/telcobase3
#export TELCOBASE_HOME=${TELCOBASE_DIR}/release
export TELCOBASE_HOME=${HOME}/telcobase_release/telcobase_release-3.3.0-64bit-RHEL7.3
export THREAD_STACK_SIZE=2097152

export PATH=$TELCOBASE_HOME/bin:~/mmdb/telcobase_scripts:/bin:~/bin/scripts:~/scripts:$PATH:/sbin:.
export LD_LIBRARY_PATH=$TELCOBASE_HOME/lib:$LD_LIBRARY_PATH


